ServerName: "Server-Name"


Rank:
  Name: "Your Rank:"


Money:
  Name: "Money:"
  Suffix: "$"
  Color: "ยง6"


  # Be careful that the string is not longer than the scoreboard is able to show
  # To split texts in multiple lines use '::'
  # The message can only be split in 3 parts

Info:
  Name: "Infos:"
  Cooldown: 60 #In Seconds
  Infos:
    - "example text::another example::last example here :)"